package io.github.gaurav1112.mirrorlint.lang;

/**
 * Recognizes machine-generated sources so the scanner can suppress their shapes: a code
 * generator's output legitimately mirrors a truth's member list on every run, so treating it as
 * drift would flag thousands of findings that no human ever wrote and no human can fix by hand.
 */
public final class GeneratedFileDetector {
    private static final int MAX_HEADER_LINES = 20;
    private static final String[] MARKERS = {
        "@generated", "Generated by", "DO NOT EDIT", "Code generated",
    };

    private GeneratedFileDetector() {}

    /** True iff any of the source's first {@value #MAX_HEADER_LINES} lines contains a known marker. */
    public static boolean isGenerated(String source) {
        String[] lines = source.split("\n", -1);
        int limit = Math.min(lines.length, MAX_HEADER_LINES);
        for (int i = 0; i < limit; i++) {
            for (String marker : MARKERS) {
                if (lines[i].contains(marker)) return true;
            }
        }
        return false;
    }
}
