package io.github.gaurav1112.mirrorlint.lang;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class GeneratedFileDetectorTest {
    @Test
    void detectsAtGeneratedMarker() {
        assertThat(GeneratedFileDetector.isGenerated("// @generated\nexport const a = 1;")).isTrue();
    }

    @Test
    void detectsGeneratedByMarker() {
        assertThat(GeneratedFileDetector.isGenerated("// Generated by protoc-gen-ts\nexport const a = 1;")).isTrue();
    }

    @Test
    void detectsDoNotEditMarker() {
        assertThat(GeneratedFileDetector.isGenerated("// DO NOT EDIT\nexport const a = 1;")).isTrue();
    }

    @Test
    void detectsCodeGeneratedMarker() {
        assertThat(GeneratedFileDetector.isGenerated("// Code generated by tool; DO NOT modify by hand.\nexport const a = 1;"))
            .isTrue();
    }

    @Test
    void plainFileIsNotGenerated() {
        assertThat(GeneratedFileDetector.isGenerated("export const a = 1;\nexport const b = 2;")).isFalse();
    }

    @Test
    void markerPastLine20IsIgnored() {
        StringBuilder source = new StringBuilder();
        for (int i = 0; i < 24; i++) {
            source.append("// filler line ").append(i).append('\n');
        }
        source.append("// DO NOT EDIT\n");
        source.append("export const a = 1;\n");

        assertThat(GeneratedFileDetector.isGenerated(source.toString())).isFalse();
    }
}
